require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/publication_contents", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # PublicationContent. As you add validations to PublicationContent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PublicationContent.create! valid_attributes
      get publication_contents_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      publication_content = PublicationContent.create! valid_attributes
      get publication_content_url(publication_content)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_publication_content_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      publication_content = PublicationContent.create! valid_attributes
      get edit_publication_content_url(publication_content)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PublicationContent" do
        expect {
          post publication_contents_url, params: { publication_content: valid_attributes }
        }.to change(PublicationContent, :count).by(1)
      end

      it "redirects to the created publication_content" do
        post publication_contents_url, params: { publication_content: valid_attributes }
        expect(response).to redirect_to(publication_content_url(PublicationContent.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PublicationContent" do
        expect {
          post publication_contents_url, params: { publication_content: invalid_attributes }
        }.to change(PublicationContent, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post publication_contents_url, params: { publication_content: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested publication_content" do
        publication_content = PublicationContent.create! valid_attributes
        patch publication_content_url(publication_content), params: { publication_content: new_attributes }
        publication_content.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the publication_content" do
        publication_content = PublicationContent.create! valid_attributes
        patch publication_content_url(publication_content), params: { publication_content: new_attributes }
        publication_content.reload
        expect(response).to redirect_to(publication_content_url(publication_content))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        publication_content = PublicationContent.create! valid_attributes
        patch publication_content_url(publication_content), params: { publication_content: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested publication_content" do
      publication_content = PublicationContent.create! valid_attributes
      expect {
        delete publication_content_url(publication_content)
      }.to change(PublicationContent, :count).by(-1)
    end

    it "redirects to the publication_contents list" do
      publication_content = PublicationContent.create! valid_attributes
      delete publication_content_url(publication_content)
      expect(response).to redirect_to(publication_contents_url)
    end
  end
end
